<Project>
  <PropertyGroup>
    <ValheimPath Condition="'$(ValheimPath)' == ''">D:\SteamLibrary\steamapps\common\Valheim</ValheimPath>
    <GaleProfile Condition="'$(GaleProfile)' == ''">$(USERPROFILE)\AppData\Roaming\com.kesomannen.gale\valheim\profiles\New Release</GaleProfile>
    <BepInExPath Condition="'$(BepInExPath)' == ''">$(GaleProfile)\BepInEx</BepInExPath>
    <BepInExCore>$(BepInExPath)\core</BepInExCore>
    <ValheimManaged>$(ValheimPath)\valheim_Data\Managed</ValheimManaged>
    <ModVersion>1.2.2</ModVersion>
    <ModDeployDir>$(GaleProfile)\BepInEx\plugins\Hardwire99-ComfortMe</ModDeployDir>
  </PropertyGroup>
</Project>
